### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by hostnameclub** [delta360/WHMCS-Gateway-Fees#1]
Hi guy,

This is a nice addon, however we need to update to have a better module:
- Rewrite an installation guide:

To install this addon module, upload a source to /modules/addons/ and extract it.
Go to Settings -> Addon Modules, active and configure price ($ and % per transaction).
- Display Name of each payment gateway. Not "code" like "paypal", "payza" or "tco". It's Paypal, Payza, 2Checkout will have a good look.
- Display on real time a fee in Add New Order

Thank you,

**Comment by ajarmoszuk** [comment]
Al right, I'll try to edit these out and make them look a bit nicer.

**Comment by hostnameclub** [comment]
Hi,

I have a little time to edit, but hooks.php should update to display currency (mine is USD) in invoice like that:

function update_gateway_fee2($vars)
{
    $paymentmethod = $vars['paymentmethod'];
    delete_query("tblinvoiceitems", "invoiceid='" . $vars[invoiceid] . "' and notes='gateway_fees'");
    $result = select_query("tbladdonmodules", "setting,value", "setting='fee_2_" . $vars['paymentmethod'] . "' or setting='fee_1_" . $vars[paymentmethod] . "'");
    while ($data = mysql_fetch_array($result)) {
        $params[$data[0]] = $data[1];
    }
    $fee1 = ($params['fee_1_' . $paymentmethod]);
    $fee2 = ($params['fee_2_' . $paymentmethod]);
    $total = InvoiceTotal($vars['invoiceid']);
    if ($total > 0) {
        $amountdue = $fee1 + $total \* $fee2 / 100;
        if ($fee1 > 0 & $fee2 > 0) {
            $d = "$" . $fee1 . ' + ' . $fee2 . "%";
        }
        elseif ($fee2 > 0) {
            $d = $fee2 . "%";
        }
        elseif ($fee1 > 0) {
            $d = $fee1;
        }
    }
    if ($d) {
        insert_query("tblinvoiceitems", array(
            "userid" => $_SESSION['uid'],
            "invoiceid" => $vars[invoiceid],
            "type" => "Fee",
            "notes" => "gateway_fees",
            "description" => getGatewayName2($vars['paymentmethod']) . " Processing Fees ($d)",
            "amount" => $amountdue,
            "taxed" => "0",
            "duedate" => "now()",
            "paymentmethod" => $vars[paymentmethod]
        ));
    }
    updateInvoiceTotal($vars[invoiceid]);
}

**Comment by ajarmoszuk** [comment]
Hi, would you mind pushing this into the repo? I'm a bit busy at the moment.
