### ISSUE TITLE
update price

### ISSUE THREAD

**Issue by ghost** [delta360/WHMCS-Gateway-Fees#5]
Hello,
Thank you for your great work !
Is it possible to update price before taking customer to payment gateway ?
Also with Paypal recurrent price is not correct, it should be product price + gateway fees, but paypal show product price only without counting payment gateway fees.
if you need more informations please do not hesitate to contact me.
Thank you,
Fathi.N

**Comment by khoipro** [comment]
Recurring Paypal (subscription) currently has same thing as you told: The payment in first payment is fine, but from second payment it is lower price than (with no fee includes).

Example:
Price with fee: $5.90
Price without fee: $5.00

Payment first time: $5.90
Payment from second time: $5.00 (recurring - auto subscription from Paypal)

**Comment by ghost** [comment]
yes but it should be price of product + fees

**Comment by rihamd2k** [comment]
I am still having the same issue. When someone subscribes through paypal it creates subscription invoice like:
first month product price $2 + (paypal transection fees $0.30) (example)
recurring charge $2

so transaction fees is only working for the first month, not for the recurring charges. we appreciate your hard work for this module. But if you please fix this problem this will be a great solution for us. In case if you want to make a premium version of this module we could purchase it for one time fees. We expect a solution from you regarding this issue. Thanks.

**Comment by hawkeye217** [comment]
+1 

Same issue, recurring charges are not getting assessed the fees.  Anyone know how to fix?
