### ISSUE TITLE
Does this still works?

### ISSUE THREAD

**Issue by TomasHurtz** [delta360/WHMCS-Gateway-Fees#7]
Is it still good for current version 7 + ?

**Comment by tutugreen** [comment]
Yes, it's still works pretty good.

**Comment by TomasHurtz** [comment]
Yes, I confirm it works great for adding a fee to a mail in payment.  

The only thing missing - there is no fee notice added to the PDF invoice or in the client email invoice.

Thank you to the devs.

**Comment by TomasHurtz** [comment]
All is working well - the only issue is - could it be individually removed from a specific client somehow (one that refuses to accept the fee !)

**Comment by TomasHurtz** [comment]
The other issue I discover is that it adds the % on top of any tax added!
