### ISSUE TITLE
Invoice created in daily cron does not send e-mail rate

### ISSUE THREAD

**Issue by mariopaglia** [delta360/WHMCS-Gateway-Fees#8]
Hello how are you?

I have used this module and realized that the invoices generated by Cron are not sent by the module.

Example:

Invoice of 10.00 + 2.00 fee, in the email, instead of sending detailed invoice with 12.00, it sends only as 10.00, and when the customer enters the WHMCS, he sees the invoice at 12.00, this creates a certain conflict with the clients, as some require that the invoice be charged in the amount that was in their emails.

How could we fix this?

**Comment by mauamolat** [comment]
I second this

**Comment by mauamolat** [comment]
Is there a fix for this?

**Comment by NikoGrano** [comment]
Im going to work on new module soonish. However, I will be asking cup of coffee for it. This module is outdated and current version of whmcs have different functionality.
